---

# see https://github.com/netbox-community/netbox/blob/develop/upgrade.sh
- name: Do migrate
  community.general.django_manage:
    app_path: "{{ netbox_app_dir }}"
    virtualenv: "{{ netbox_venv_dir }}"
    command: migrate
  become: yes
  become_user: "{{ netbox_user }}"

- name: Do trace_paths
  community.general.django_manage:
    app_path: "{{ netbox_app_dir }}"
    virtualenv: "{{ netbox_venv_dir }}"
    command: trace_paths --no-input
  become: yes
  become_user: "{{ netbox_user }}"

- name: Do collectstatic
  community.general.django_manage:
    app_path: "{{ netbox_app_dir }}"
    virtualenv: "{{ netbox_venv_dir }}"
    command: collectstatic
  become: yes
  become_user: "{{ netbox_user }}"

- name: Do remove_stale_contenttypes
  community.general.django_manage:
    app_path: "{{ netbox_app_dir }}"
    virtualenv: "{{ netbox_venv_dir }}"
    command: remove_stale_contenttypes --no-input
  become: yes
  become_user: "{{ netbox_user }}"

- name: Do clearsessions
  community.general.django_manage:
    app_path: "{{ netbox_app_dir }}"
    virtualenv: "{{ netbox_venv_dir }}"
    command: clearsessions
  become: yes
  become_user: "{{ netbox_user }}"

- name: Do createsuperuser
  environment:
    DJANGO_SUPERUSER_CREATE: true
    DJANGO_SUPERUSER_USERNAME: "{{ netbox_superuser_name }}"
    DJANGO_SUPERUSER_EMAIL: "{{ netbox_superuser_email }}"
    DJANGO_SUPERUSER_PASSWORD: "{{ netbox_superuser_password }}"
  community.general.django_manage:
    app_path: "{{ netbox_app_dir }}"
    virtualenv: "{{ netbox_venv_dir }}"
    command: createsuperuser --no-input
  become: yes
  become_user: "{{ netbox_user }}"
