---

- name: Create netbox.conf for supervisor
  ansible.builtin.template:
    src: supervisor.netbox.conf.j2
    dest: "{{ netbox_supervisor_conf_file }}"
    mode: "0644"

- name: Add netbox to supervisor
  community.general.supervisorctl:
    name: "{{ netbox_service }}"
    state: present

- name: Add netbox_rq to supervisor
  community.general.supervisorctl:
    name: "{{ netbox_service_rq }}"
    state: present
