---

- name: Install netbox_required_packages
  ansible.builtin.pkgng:
    name: "{{ netbox_required_packages }}"
    state: present

- name: Install netbox_extra_packages
  ansible.builtin.pkgng:
    name: "{{ netbox_extra_packages }}"
    state: present

- name: Create netbox_rq rc script
  template:
    src: netbox_rq.rc.j2
    dest: /usr/local/etc/rc.d/netbox_rq
    mode: '0755'
  notify:
    - "{{ __fact_netbox_handler_for_netbox_rq }}"

- name: Create netbox rc script
  template:
    src: netbox.rc.j2
    dest: /usr/local/etc/rc.d/netbox
    mode: '0755'
  notify:
    - "{{ __fact_netbox_handler_for_netbox }}"

- name: Enable netbox_service
  ansible.builtin.service:
    name: "{{ netbox_service }}"
    enabled: yes

- name: Enable netbox_service_rq
  ansible.builtin.service:
    name: "{{ netbox_service_rq }}"
    enabled: yes

- name: Create /etc/rc.conf.d/netbox
  ansible.builtin.template:
    src: netbox.rc.conf.j2
    dest: "/etc/rc.conf.d/{{ netbox_service }}"
    mode: "0644"
    validate: sh -n %s
  notify:
    - "{{ __fact_netbox_handler_for_netbox }}"

- name: Create /etc/rc.conf.d/netbox_rq
  ansible.builtin.template:
    src: netbox_rq.rc.conf.j2
    dest: "/etc/rc.conf.d/{{ netbox_service_rq }}"
    mode: "0644"
    validate: sh -n %s
  notify:
    - "{{ __fact_netbox_handler_for_netbox_rq }}"
