---
# tasks file for ansible-role-netbox

- name: "Include variables from {{ ansible_os_family }}.yml"
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - 'vars'

- name: Set netbox handler names
  set_fact:
    __fact_netbox_handler_for_netbox: "{% if netbox_using_supervisor %}Restart netbox via supervisor{% else %}Restart netbox via service{% endif %}"
    __fact_netbox_handler_for_netbox_rq: "{% if netbox_using_supervisor %}Restart netbox_rq via supervisor{% else %}Restart netbox_rq via service{% endif %}"

- name: Create netbox_group
  ansible.builtin.group:
    name: "{{ netbox_group }}"

- name: Create netbox_user
  ansible.builtin.user:
    name: "{{ netbox_user }}"
    create_home: yes
    group: "{{ netbox_group }}"
    home: "{{ netbox_home_dir }}"

- name: Ensure netbox_home_dir is readable by others
  ansible.builtin.file:
    path: "{{ netbox_home_dir }}"
    mode: "0755"

- name: Create netbox_log_dir
  ansible.builtin.file:
    path: "{{ netbox_log_dir }}"
    owner: "{{ netbox_user }}"
    group: "{{ netbox_group }}"
    mode: "0755"
    state: directory
  notify: "{{ __fact_netbox_handler_for_netbox }}"

- name: "Include install-{{ ansible_os_family }}.yml"
  include: "install-{{ ansible_os_family }}.yml"

- name: Install netbox via git
  ansible.builtin.git:
    repo: "{{ netbox_git_repo }}"
    version: "{{ netbox_git_version }}"
    update: "{{ netbox_git_update }}"
    dest: "{{ netbox_root_dir }}"
  register: __netbox_install_netbox
  become: yes
  become_user: "{{ netbox_user }}"
  notify:
    - "{{ __fact_netbox_handler_for_netbox }}"
    - "{{ __fact_netbox_handler_for_netbox_rq }}"

- name: Install pip and wheel
  ansible.builtin.pip:
    name:
      - pip
      - wheel
    extra_args: "--upgrade"
    virtualenv: "{{ netbox_venv_dir }}"
    virtualenv_command: "{{ ansible_python['executable'] }} -m venv"
  become: true
  become_user: "{{ netbox_user }}"

- name: Install pip packages listed in requirements.txt
  ansible.builtin.pip:
    requirements: "{{ netbox_root_dir }}/requirements.txt"
    extra_args: ""
    virtualenv: "{{ netbox_venv_dir }}"
    virtualenv_command: "{{ ansible_python['executable'] }} -m venv"
  become: true
  become_user: "{{ netbox_user }}"
  notify:
    - "{{ __fact_netbox_handler_for_netbox }}"
    - "{{ __fact_netbox_handler_for_netbox_rq }}"
  # XXX disable HTTP/2. `cargo build` fails when building cryptography on
  # macos GitHub Actions runner. this does not happen on FreeBSD, but on
  # OpenBSD.
  #
  # [92] Stream error in the HTTP/2 framing layer (HTTP/2 stream 3 was not closed cleanly before end of the underlying stream)
  #
  # libcurl, which cargo uses to download files, reports an error but cargo
  # does not retry.
  #
  # https://github.com/rust-lang/cargo/issues/6513
  # https://github.com/rust-lang/cargo/pull/8102
  environment:
    CARGO_HTTP_MULTIPLEXING: "false"

- name: Create local_requirements.txt
  ansible.builtin.template:
    src: local_requirements.txt.j2
    dest: "{{ netbox_root_dir }}/local_requirements.txt"
    mode: "0644"
    owner: "{{ netbox_user }}"
    group: "{{ netbox_group }}"
  become: true
  become_user: "{{ netbox_user }}"
  notify:
    - "{{ __fact_netbox_handler_for_netbox }}"
    - "{{ __fact_netbox_handler_for_netbox_rq }}"

- name: Install pip packages listed in local_requirements.txt
  ansible.builtin.pip:
    requirements: "{{ netbox_root_dir }}/local_requirements.txt"
    extra_args: ""
    virtualenv: "{{ netbox_venv_dir }}"
    virtualenv_command: "{{ ansible_python['executable'] }} -m venv"
  register: __netbox_register_local_requirements
  become: true
  become_user: "{{ netbox_user }}"
  notify:
    - "{{ __fact_netbox_handler_for_netbox }}"
    - "{{ __fact_netbox_handler_for_netbox_rq }}"
  environment:
    CARGO_HTTP_MULTIPLEXING: "false"

- name: Create configuration.py
  ansible.builtin.template:
    src: configuration.py.j2
    dest: "{{ netbox_conf_file }}"
    owner: "{{ netbox_user }}"
    group: "{{ netbox_group }}"
    mode: '0640'
    validate: "{{ ansible_python['executable'] }} -m py_compile %s"
  notify:
    - "{{ __fact_netbox_handler_for_netbox }}"
    - "{{ __fact_netbox_handler_for_netbox_rq }}"

- name: Create gunicorn.py
  ansible.builtin.template:
    src: gunicorn.py.j2
    dest: "{{ netbox_gunicorn_conf_file }}"
    mode: "0644"
    owner: "{{ netbox_user }}"
    group: "{{ netbox_group }}"
    validate: "{{ ansible_python['executable'] }} -m py_compile %s"
  notify:
    - "{{ __fact_netbox_handler_for_netbox }}"

- name: Create netbox_static_dir
  ansible.builtin.file:
    path: "{{ netbox_static_dir }}"
    owner: "{{ netbox_user }}"
    group: "{{ netbox_group }}"
    mode: '0755'
    state: directory

- name: Wait for redis server (tasks)
  ansible.builtin.wait_for:
    host: "{{ netbox_redis_tasks_host }}"
    port: "{{ netbox_redis_tasks_port }}"
    delay: "{{ netbox_redis_wait_for_delay }}"
    sleep: "{{ netbox_redis_wait_for_sleep }}"

- name: Wait for redis server (caching)
  ansible.builtin.wait_for:
    host: "{{ netbox_redis_caching_host }}"
    port: "{{ netbox_redis_caching_port }}"
    delay: "{{ netbox_redis_wait_for_delay }}"
    sleep: "{{ netbox_redis_wait_for_sleep }}"

- name: Wait for postgresql
  ansible.builtin.wait_for:
    host: "{{ netbox_db_host }}"
    port: "{{ netbox_db_port }}"
    delay: "{{ netbox_db_wait_for_delay }}"
    sleep: "{{ netbox_db_wait_for_sleep }}"

- name: Include init-netbox.yml
  include: init-netbox.yml
  when:
    - __netbox_install_netbox['changed']

- name: Do migrate when local_requirements changed
  community.general.django_manage:
    app_path: "{{ netbox_app_dir }}"
    virtualenv: "{{ netbox_venv_dir }}"
    command: migrate
  become: yes
  become_user: "{{ netbox_user }}"
  notify:
    - "{{ __fact_netbox_handler_for_netbox }}"
  when:
    # XXX this needs to be called before the end of role play. when a hanlder
    # is used, it would be at the end of the entire play, and too late.
    - __netbox_register_local_requirements['changed']  # noqa no-handler

- name: Do collectstatic when local_requirements changed
  community.general.django_manage:
    app_path: "{{ netbox_app_dir }}"
    virtualenv: "{{ netbox_venv_dir }}"
    command: collectstatic
  become: yes
  become_user: "{{ netbox_user }}"
  notify:
    - "{{ __fact_netbox_handler_for_netbox }}"
  when:
    - __netbox_register_local_requirements['changed']  # noqa no-handler

- name: Start netbox via service
  ansible.builtin.service:
    name: "{{ netbox_service }}"
    state: started
  when:
    - not netbox_using_supervisor

- name: Start netbox_rq via service
  ansible.builtin.service:
    name: "{{ netbox_service_rq }}"
    state: started
  when:
    - not netbox_using_supervisor

- name: Start netbox via supervisor
  community.general.supervisorctl:
    name: "{{ netbox_service }}"
    state: started
  when:
    - netbox_using_supervisor

- name: Start netbox_rq via supervisor
  community.general.supervisorctl:
    name: "{{ netbox_service_rq }}"
    state: started
  when:
    - netbox_using_supervisor

- name: Wait for netbox
  ansible.builtin.wait_for:
    host: "{{ netbox_bind_address }}"
    port: "{{ netbox_bind_port }}"
    delay: "{{ netbox_wait_for_delay }}"
    sleep: "{{ netbox_wait_for_sleep }}"
