---
# tasks file for ansible-role-netbox

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ netbox_log_dir }}"
    mode: 0755
    owner: "{{ netbox_user }}"
    group: "{{ netbox_group }}"
    state: directory
  notify: Restart netbox

- name: Create db directory
  file:
    path: "{{ netbox_db_dir }}"
    mode: 0755
    owner: "{{ netbox_user }}"
    group: "{{ netbox_group }}"
    state: directory
  notify: Restart netbox

- name: Create netbox.conf
  template:
    src: netbox.conf.j2
    dest: "{{ netbox_conf_file }}"
    validate: echo %s
  notify: Restart netbox

- name: Start netbox
  service:
    name: "{{ netbox_service }}"
    enabled: true
    state: started
