---
# tasks file for ansible-role-netbox

- name: "Inlcude variables from {{ ansible_os_family }}.yml"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Include install-{{ ansible_os_family }}.yml"
  include: "install-{{ ansible_os_family }}.yml"

- name: Create configuration.py
  ansible.builtin.template:
    src: configuration.py.j2
    dest: "{{ netbox_conf_file }}"
    owner: "{{ netbox_user }}"
    group: "{{ netbox_group }}"
    mode: '0640'
    validate: "{{ ansible_python['executable'] }} -m py_compile %s"
  notify: Restart netbox

- name: Wait for redis server (tasks)
  ansible.builtin.wait_for:
    host: "{{ netbox_redis_tasks_host }}"
    port: "{{ netbox_redis_tasks_port }}"
    delay: "{{ netbox_redis_wait_for_delay }}"
    sleep: "{{ netbox_redis_wait_for_sleep }}"

- name: Wait for redis server (caching)
  ansible.builtin.wait_for:
    host: "{{ netbox_redis_caching_host }}"
    port: "{{ netbox_redis_caching_port }}"
    delay: "{{ netbox_redis_wait_for_delay }}"
    sleep: "{{ netbox_redis_wait_for_sleep }}"

- name: Wait for postgrsql
  ansible.builtin.wait_for:
    host: "{{ netbox_db_host }}"
    port: "{{ netbox_db_port }}"
    delay: "{{ netbox_db_wait_for_delay }}"
    sleep: "{{ netbox_db_wait_for_sleep }}"

- name: Include init_netbox.yml
  include: init_netbox.yml
  when:
    - __netbox_install_netbox['changed']

- name: Start netbox_rq
  ansible.builtin.service:
    name: "{{ netbox_service_rq }}"
    state: started

- name: Start netbox
  ansible.builtin.service:
    name: "{{ netbox_service }}"
    state: started

- name: Wait for netbox
  ansible.builtin.wait_for:
    host: "{{ netbox_bind_address }}"
    port: "{{ netbox_bind_port }}"
    delay: "{{ netbox_wait_for_delay }}"
    sleep: "{{ netbox_wait_for_sleep }}"
